{{- if .Values.gcp.serviceAccount.enabled }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ include "service.fullname" . }}-sa
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
    cnrm.cloud.google.com/project-id: {{ .Values.gcp.projectId }}
spec:
  description: GCP service account for workload identity
  displayName: {{ include "service.fullname" . }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ include "service.fullname" . }}-wif
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    cnrm.cloud.google.com/project-id: {{ .Values.gcp.projectId }}
spec:
  member: serviceAccount:{{ .Values.gcp.projectId }}.svc.id.goog[{{ .Release.Namespace }}/{{ include "service.serviceAccountName" . }}]
  resourceRef:
    kind: IAMServiceAccount
    name: {{ include "service.fullname" . }}-sa
  role: roles/iam.workloadIdentityUser
{{- end }}
