{{- if .Values.gcp.database.enabled }}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: {{ include "service.fullname" . }}-sql-user
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
    cnrm.cloud.google.com/project-id: {{ .Values.gcp.projectId }}
    # cnrm.cloud.google.com/deletion-policy: abandon
spec:
  instanceRef:
    external: {{ .Values.gcp.database.instanceName }}
  password:
    valueFrom:
      secretKeyRef:
        name: {{ include "service.fullname" . }}-secret-env
        key: DB_PASSWORD
  resourceID: {{ include "service.fullname" . }}
{{- end }}
