{{- if .Values.gcp.storage.enabled }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: {{ include "service.fullname" . }}-storage-iam
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    cnrm.cloud.google.com/project-id: {{ .Values.gcp.projectId }}
spec:
  bindings:
    - members:
        {{- if .Values.gcp.serviceAccount.enabled }}
        - memberFrom:
            serviceAccountRef:
              name: {{ include "service.fullname" . }}-sa
        {{- end }}
        {{- range .Values.gcp.storage.objectAdmins }}
        - member: {{ . }}
        {{- end }}
      role: roles/storage.objectAdmin
  resourceRef:
    kind: StorageBucket
    name: {{ include "service.fullname" . }}-bucket
{{- end }}
